package com.teleconnect.analytics_service.service.impl;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.teleconnect.analytics_service.dto.response.*;
import com.teleconnect.analytics_service.entity.TelecomReport;
import com.teleconnect.analytics_service.exception.AnalyticsException;
import com.teleconnect.analytics_service.exception.ResourceNotFoundException;
import com.teleconnect.analytics_service.repository.TelecomReportRepository;
import com.teleconnect.analytics_service.service.ExportService;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.LinkedHashMap;
import java.util.Map;

@Slf4j
@Service
public class ExportServiceImpl implements ExportService {

    private static final float MARGIN = 50f;
    private static final float LINE_HEIGHT = 18f;
    private static final float PAGE_WIDTH = PDRectangle.A4.getWidth();
    private static final float CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;

    private final TelecomReportRepository telecomReportRepository;
    private final ObjectMapper objectMapper;

    public ExportServiceImpl(TelecomReportRepository telecomReportRepository,
                             ObjectMapper objectMapper) {
        this.telecomReportRepository = telecomReportRepository;
        this.objectMapper = objectMapper;
    }

    // ─── Saved Report Export ────────────────────────────────────────────────

    @Override
    public byte[] exportReportAsPdf(Long reportId) throws IOException {
        log.info("Exporting report as PDF reportId={}", reportId);
        TelecomReport report = findReport(reportId);
        Map<String, Object> metrics = parseMetrics(report.getMetrics());

        Map<String, String> rows = new LinkedHashMap<>();
        rows.put("Report ID", String.valueOf(report.getReportId()));
        rows.put("Scope", report.getScope().name());
        rows.put("Scope Value", report.getScopeValue());
        rows.put("Period Start", report.getPeriodStart().toString());
        rows.put("Period End", report.getPeriodEnd().toString());
        rows.put("Generated Date", report.getGeneratedDate().toString());
        rows.put("Generated By", report.getGeneratedBy() != null ? report.getGeneratedBy().toString() : "System");
        rows.put("──────────", "──────────────────");
        for (Map.Entry<String, Object> e : metrics.entrySet()) {
            rows.put(e.getKey(), String.valueOf(e.getValue()));
        }

        return buildPdf("TeleConnect Analytics Report", "Module 2.7 — Telecom Analytics & Reporting", rows);
    }

    @Override
    public byte[] exportReportAsCsv(Long reportId) {
        log.info("Exporting report as CSV reportId={}", reportId);
        TelecomReport report = findReport(reportId);
        Map<String, Object> metrics = parseMetrics(report.getMetrics());

        StringBuilder sb = new StringBuilder();
        sb.append("Field,Value\n");
        sb.append("Report ID,").append(report.getReportId()).append("\n");
        sb.append("Scope,").append(report.getScope()).append("\n");
        sb.append("Scope Value,").append(csvEscape(report.getScopeValue())).append("\n");
        sb.append("Period Start,").append(report.getPeriodStart()).append("\n");
        sb.append("Period End,").append(report.getPeriodEnd()).append("\n");
        sb.append("Generated Date,").append(report.getGeneratedDate()).append("\n");
        sb.append("Generated By,").append(report.getGeneratedBy() != null ? report.getGeneratedBy() : "System").append("\n");
        for (Map.Entry<String, Object> e : metrics.entrySet()) {
            sb.append(csvEscape(e.getKey())).append(",").append(csvEscape(String.valueOf(e.getValue()))).append("\n");
        }
        return sb.toString().getBytes();
    }

    @Override
    public byte[] exportDashboardAsPdf(DashboardResponse data) throws IOException {
        log.info("Exporting dashboard as PDF");
        Map<String, String> rows = new LinkedHashMap<>();

        if (data.getKpis() != null) {
            DashboardResponse.KPIMetrics k = data.getKpis();
            rows.put("Active Subscribers", String.valueOf(k.getActiveSubscribers()));
            rows.put("Churn Rate (%)", String.valueOf(k.getChurnRate()));
            rows.put("ARPU", String.valueOf(k.getArpu()));
            rows.put("Collection Efficiency (%)", String.valueOf(k.getCollectionEfficiency()));
            rows.put("SLA Compliance (%)", String.valueOf(k.getSlaCompliance()));
            rows.put("Data Consumption (MB)", String.valueOf(k.getDataConsumption()));
            rows.put("Fault Count", String.valueOf(k.getFaultCount()));
            rows.put("Dispute Rate (%)", String.valueOf(k.getDisputeRate()));
        }

        rows.put("──────────", "──────────────────");
        rows.put("Graphs Included", "6");
        rows.put("1", "Data Consumption Trend");
        rows.put("2", "ARPU by Account Type");
        rows.put("3", "Churn Distribution by Segment");
        rows.put("4", "Overdue Invoices by Age");
        rows.put("5", "Subscriber Growth Trend");
        rows.put("6", "Fault Frequency by Priority");

        if (data.getRegions() != null && data.getRegions().getSubscribersByRegion() != null) {
            rows.put("────────── Region ──────────", "──────────────────");
            data.getRegions().getSubscribersByRegion().forEach((region, value) ->
                    rows.put("Subscribers - " + region, String.valueOf(value)));
        }

        if (data.getSegments() != null && data.getSegments().getSubscribersByAccountType() != null) {
            rows.put("────────── Segment ──────────", "──────────────────");
            data.getSegments().getSubscribersByAccountType().forEach((type, value) ->
                    rows.put("Subscribers - " + type, String.valueOf(value)));
        }

        return buildPdf("TeleConnect Executive Dashboard", "Module 4.7 — Telecom Analytics & Reporting", rows);
    }

    // ─── ARPU ────────────────────────────────────────────────────────────────

    @Override
    public byte[] exportArpuAsPdf(ARPUReportResponse data) throws IOException {
        log.info("Exporting ARPU report as PDF cycleId={}", data.getCycleId());
        Map<String, String> rows = new LinkedHashMap<>();
        rows.put("Billing Cycle ID", String.valueOf(data.getCycleId()));
        rows.put("Scope", data.getScope());
        rows.put("Scope Value", data.getScopeValue());
        rows.put("Active Subscribers", String.valueOf(data.getActiveSubscribers()));
        rows.put("Total Revenue", String.valueOf(data.getTotalRevenue()));
        rows.put("ARPU (Overall)", String.valueOf(data.getArpuOverall()));
        rows.put("ARPU (Prepaid)", String.valueOf(data.getArpuPrepaid()));
        rows.put("ARPU (Postpaid)", String.valueOf(data.getArpuPostpaid()));
        rows.put("ARPU (Enterprise)", String.valueOf(data.getArpuEnterprise()));
        if (data.getArpuByRegion() != null) {
            data.getArpuByRegion().forEach((region, arpu) ->
                    rows.put("ARPU " + region, String.valueOf(arpu)));
        }
        return buildPdf("ARPU Report", "Average Revenue Per User Analysis", rows);
    }

    @Override
    public byte[] exportArpuAsCsv(ARPUReportResponse data) {
        log.info("Exporting ARPU report as CSV cycleId={}", data.getCycleId());
        StringBuilder sb = new StringBuilder();
        sb.append("Metric,Value\n");
        sb.append("Billing Cycle ID,").append(data.getCycleId()).append("\n");
        sb.append("Scope,").append(data.getScope()).append("\n");
        sb.append("Scope Value,").append(csvEscape(data.getScopeValue())).append("\n");
        sb.append("Active Subscribers,").append(data.getActiveSubscribers()).append("\n");
        sb.append("Total Revenue,").append(data.getTotalRevenue()).append("\n");
        sb.append("ARPU Overall,").append(data.getArpuOverall()).append("\n");
        sb.append("ARPU Prepaid,").append(data.getArpuPrepaid()).append("\n");
        sb.append("ARPU Postpaid,").append(data.getArpuPostpaid()).append("\n");
        sb.append("ARPU Enterprise,").append(data.getArpuEnterprise()).append("\n");
        if (data.getArpuByRegion() != null) {
            data.getArpuByRegion().forEach((region, arpu) ->
                    sb.append("ARPU ").append(region).append(",").append(arpu).append("\n"));
        }
        return sb.toString().getBytes();
    }

    // ─── Churn ────────────────────────────────────────────────────────────────

    @Override
    public byte[] exportChurnAsPdf(ChurnReportResponse data) throws IOException {
        log.info("Exporting churn report as PDF periodStart={} periodEnd={}", data.getPeriodStart(), data.getPeriodEnd());
        Map<String, String> rows = new LinkedHashMap<>();
        rows.put("Period Start", String.valueOf(data.getPeriodStart()));
        rows.put("Period End", String.valueOf(data.getPeriodEnd()));
        rows.put("Region", data.getRegion() != null ? data.getRegion() : "ALL");
        rows.put("Subscribers at Period Start", String.valueOf(data.getSubscribersAtPeriodStart()));
        rows.put("Terminated Accounts", String.valueOf(data.getTerminatedAccounts()));
        rows.put("Ported Out Lines", String.valueOf(data.getPortedOutLines()));
        rows.put("Gross Churned", String.valueOf(data.getGrossChurned()));
        rows.put("Churn Rate (%)", String.valueOf(data.getChurnRate()));
        rows.put("High Churn Alert", data.isHighChurnAlert() ? "YES" : "NO");
        rows.put("At-Risk Account Count", String.valueOf(data.getAtRiskCount()));
        return buildPdf("Churn Analysis Report", "Subscriber Churn & Retention Analysis", rows);
    }

    @Override
    public byte[] exportChurnAsCsv(ChurnReportResponse data) {
        log.info("Exporting churn report as CSV periodStart={} periodEnd={}", data.getPeriodStart(), data.getPeriodEnd());
        StringBuilder sb = new StringBuilder();
        sb.append("Metric,Value\n");
        sb.append("Period Start,").append(data.getPeriodStart()).append("\n");
        sb.append("Period End,").append(data.getPeriodEnd()).append("\n");
        sb.append("Region,").append(data.getRegion() != null ? data.getRegion() : "ALL").append("\n");
        sb.append("Subscribers at Period Start,").append(data.getSubscribersAtPeriodStart()).append("\n");
        sb.append("Terminated Accounts,").append(data.getTerminatedAccounts()).append("\n");
        sb.append("Ported Out Lines,").append(data.getPortedOutLines()).append("\n");
        sb.append("Gross Churned,").append(data.getGrossChurned()).append("\n");
        sb.append("Churn Rate (%),").append(data.getChurnRate()).append("\n");
        sb.append("High Churn Alert,").append(data.isHighChurnAlert() ? "YES" : "NO").append("\n");
        sb.append("At-Risk Account Count,").append(data.getAtRiskCount()).append("\n");
        if (data.getAtRiskAccountIds() != null && !data.getAtRiskAccountIds().isEmpty()) {
            sb.append("At-Risk Account IDs,\"").append(data.getAtRiskAccountIds()).append("\"\n");
        }
        return sb.toString().getBytes();
    }

    // ─── Network Utilisation ─────────────────────────────────────────────────

    @Override
    public byte[] exportNetworkUtilisationAsPdf(NetworkUtilisationResponse data) throws IOException {
        log.info("Exporting network utilisation report as PDF cycleId={} region={}", data.getCycleId(), data.getRegion());
        Map<String, String> rows = new LinkedHashMap<>();
        rows.put("Billing Cycle ID", String.valueOf(data.getCycleId()));
        rows.put("Region", data.getRegion() != null ? data.getRegion() : "ALL");
        rows.put("Total Data Used (MB)", String.valueOf(data.getTotalDataUsedMb()));
        rows.put("Total Voice Used (Min)", String.valueOf(data.getTotalVoiceUsedMin()));
        rows.put("Total SMS Used", String.valueOf(data.getTotalSmsUsed()));
        rows.put("Subscriber Count", String.valueOf(data.getSubscriberCount()));
        rows.put("Avg Data Per Subscriber (MB)", String.format("%.2f", data.getAvgDataPerSubscriberMb()));
        rows.put("Avg Voice Per Subscriber (Min)", String.format("%.2f", data.getAvgVoicePerSubscriberMin()));
        return buildPdf("Network Utilisation Report", "Data, Voice & SMS Consumption Analysis", rows);
    }

    @Override
    public byte[] exportNetworkUtilisationAsCsv(NetworkUtilisationResponse data) {
        log.info("Exporting network utilisation report as CSV cycleId={} region={}", data.getCycleId(), data.getRegion());
        StringBuilder sb = new StringBuilder();
        sb.append("Metric,Value\n");
        sb.append("Billing Cycle ID,").append(data.getCycleId()).append("\n");
        sb.append("Region,").append(data.getRegion() != null ? data.getRegion() : "ALL").append("\n");
        sb.append("Total Data Used (MB),").append(data.getTotalDataUsedMb()).append("\n");
        sb.append("Total Voice Used (Min),").append(data.getTotalVoiceUsedMin()).append("\n");
        sb.append("Total SMS Used,").append(data.getTotalSmsUsed()).append("\n");
        sb.append("Subscriber Count,").append(data.getSubscriberCount()).append("\n");
        sb.append("Avg Data Per Subscriber (MB),").append(String.format("%.2f", data.getAvgDataPerSubscriberMb())).append("\n");
        sb.append("Avg Voice Per Subscriber (Min),").append(String.format("%.2f", data.getAvgVoicePerSubscriberMin())).append("\n");
        return sb.toString().getBytes();
    }

    // ─── SLA Compliance ───────────────────────────────────────────────────────

    @Override
    public byte[] exportSLAComplianceAsPdf(SLAComplianceResponse data) throws IOException {
        log.info("Exporting SLA compliance report as PDF periodStart={} periodEnd={}", data.getPeriodStart(), data.getPeriodEnd());
        Map<String, String> rows = new LinkedHashMap<>();
        rows.put("Period Start", String.valueOf(data.getPeriodStart()));
        rows.put("Period End", String.valueOf(data.getPeriodEnd()));
        rows.put("Overall Compliance Rate (%)", String.valueOf(data.getOverallComplianceRate()));
        rows.put("Total Tickets Closed", String.valueOf(data.getTotalTicketsClosed()));
        rows.put("Total Breaches", String.valueOf(data.getTotalBreaches()));
        rows.put("Escalated Count", String.valueOf(data.getEscalatedCount()));
        rows.put("Avg Resolution Time (Hours)", String.valueOf(data.getAvgResolutionHours()));
        if (data.getStatsByPriority() != null) {
            rows.put("──────────", "──────────────────");
            data.getStatsByPriority().forEach((priority, stats) -> {
                rows.put(priority + " — Total", String.valueOf(stats.getTotal()));
                rows.put(priority + " — SLA Met", String.valueOf(stats.getSlaMet()));
                rows.put(priority + " — Breached", String.valueOf(stats.getSlaBreached()));
                rows.put(priority + " — Compliance (%)", String.format("%.2f", stats.getComplianceRate()));
                rows.put(priority + " — Avg Hours", String.format("%.2f", stats.getAvgResolutionHours()));
            });
        }
        return buildPdf("SLA Compliance Report", "Fault Ticket Resolution & SLA Adherence", rows);
    }

    @Override
    public byte[] exportSLAComplianceAsCsv(SLAComplianceResponse data) {
        log.info("Exporting SLA compliance report as CSV periodStart={} periodEnd={}", data.getPeriodStart(), data.getPeriodEnd());
        StringBuilder sb = new StringBuilder();
        sb.append("Metric,Value\n");
        sb.append("Period Start,").append(data.getPeriodStart()).append("\n");
        sb.append("Period End,").append(data.getPeriodEnd()).append("\n");
        sb.append("Overall Compliance Rate (%),").append(data.getOverallComplianceRate()).append("\n");
        sb.append("Total Tickets Closed,").append(data.getTotalTicketsClosed()).append("\n");
        sb.append("Total Breaches,").append(data.getTotalBreaches()).append("\n");
        sb.append("Escalated Count,").append(data.getEscalatedCount()).append("\n");
        sb.append("Avg Resolution Time (Hours),").append(data.getAvgResolutionHours()).append("\n");
        if (data.getStatsByPriority() != null) {
            sb.append("\nPriority,Total,SLA Met,Breached,Compliance (%),Avg Hours\n");
            data.getStatsByPriority().forEach((priority, stats) ->
                    sb.append(priority).append(",")
                      .append(stats.getTotal()).append(",")
                      .append(stats.getSlaMet()).append(",")
                      .append(stats.getSlaBreached()).append(",")
                      .append(String.format("%.2f", stats.getComplianceRate())).append(",")
                      .append(String.format("%.2f", stats.getAvgResolutionHours())).append("\n"));
        }
        return sb.toString().getBytes();
    }

    // ─── Collection Efficiency ────────────────────────────────────────────────

    @Override
    public byte[] exportCollectionEfficiencyAsPdf(CollectionEfficiencyResponse data) throws IOException {
        log.info("Exporting collection efficiency report as PDF cycleId={}", data.getCycleId());
        Map<String, String> rows = new LinkedHashMap<>();
        rows.put("Billing Cycle ID", String.valueOf(data.getCycleId()));
        rows.put("Total Invoiced", String.valueOf(data.getTotalInvoiced()));
        rows.put("Total Collected", String.valueOf(data.getTotalCollected()));
        rows.put("Collection Efficiency (%)", String.valueOf(data.getCollectionEfficiencyPct()));
        rows.put("──────────", "──────────────────");
        rows.put("Overdue Count (0–30 days)", String.valueOf(data.getOverdueCount0to30()));
        rows.put("Overdue Amount (0–30 days)", String.valueOf(data.getOverdueAmount0to30()));
        rows.put("Overdue Count (31–60 days)", String.valueOf(data.getOverdueCount31to60()));
        rows.put("Overdue Amount (31–60 days)", String.valueOf(data.getOverdueAmount31to60()));
        rows.put("Overdue Count (60+ days)", String.valueOf(data.getOverdueCount60plus()));
        rows.put("Overdue Amount (60+ days)", String.valueOf(data.getOverdueAmount60plus()));
        return buildPdf("Collection Efficiency Report", "Invoice Collection & Overdue Ageing Analysis", rows);
    }

    @Override
    public byte[] exportCollectionEfficiencyAsCsv(CollectionEfficiencyResponse data) {
        log.info("Exporting collection efficiency report as CSV cycleId={}", data.getCycleId());
        StringBuilder sb = new StringBuilder();
        sb.append("Metric,Value\n");
        sb.append("Billing Cycle ID,").append(data.getCycleId()).append("\n");
        sb.append("Total Invoiced,").append(data.getTotalInvoiced()).append("\n");
        sb.append("Total Collected,").append(data.getTotalCollected()).append("\n");
        sb.append("Collection Efficiency (%),").append(data.getCollectionEfficiencyPct()).append("\n");
        sb.append("Overdue Count (0-30 days),").append(data.getOverdueCount0to30()).append("\n");
        sb.append("Overdue Amount (0-30 days),").append(data.getOverdueAmount0to30()).append("\n");
        sb.append("Overdue Count (31-60 days),").append(data.getOverdueCount31to60()).append("\n");
        sb.append("Overdue Amount (31-60 days),").append(data.getOverdueAmount31to60()).append("\n");
        sb.append("Overdue Count (60+ days),").append(data.getOverdueCount60plus()).append("\n");
        sb.append("Overdue Amount (60+ days),").append(data.getOverdueAmount60plus()).append("\n");
        return sb.toString().getBytes();
    }

    // ─── Subscriber Growth ────────────────────────────────────────────────────

    @Override
    public byte[] exportSubscriberGrowthAsPdf(SubscriberGrowthResponse data) throws IOException {
        log.info("Exporting subscriber growth report as PDF periodStart={} periodEnd={}", data.getPeriodStart(), data.getPeriodEnd());
        Map<String, String> rows = new LinkedHashMap<>();
        rows.put("Period Start", String.valueOf(data.getPeriodStart()));
        rows.put("Period End", String.valueOf(data.getPeriodEnd()));
        rows.put("Gross Adds", String.valueOf(data.getGrossAdds()));
        rows.put("Terminations", String.valueOf(data.getTerminations()));
        rows.put("Net Adds", String.valueOf(data.getNetAdds()));
        rows.put("Active SIM Activations", String.valueOf(data.getActiveSIMActivations()));
        rows.put("──────────", "──────────────────");
        rows.put("Prepaid Adds", String.valueOf(data.getPrepaidAdds()));
        rows.put("Postpaid Adds", String.valueOf(data.getPostpaidAdds()));
        rows.put("Enterprise Adds", String.valueOf(data.getEnterpriseAdds()));
        return buildPdf("Subscriber Growth Report", "Activations, Net Adds & Termination Analysis", rows);
    }

    @Override
    public byte[] exportSubscriberGrowthAsCsv(SubscriberGrowthResponse data) {
        log.info("Exporting subscriber growth report as CSV periodStart={} periodEnd={}", data.getPeriodStart(), data.getPeriodEnd());
        StringBuilder sb = new StringBuilder();
        sb.append("Metric,Value\n");
        sb.append("Period Start,").append(data.getPeriodStart()).append("\n");
        sb.append("Period End,").append(data.getPeriodEnd()).append("\n");
        sb.append("Gross Adds,").append(data.getGrossAdds()).append("\n");
        sb.append("Terminations,").append(data.getTerminations()).append("\n");
        sb.append("Net Adds,").append(data.getNetAdds()).append("\n");
        sb.append("Active SIM Activations,").append(data.getActiveSIMActivations()).append("\n");
        sb.append("Prepaid Adds,").append(data.getPrepaidAdds()).append("\n");
        sb.append("Postpaid Adds,").append(data.getPostpaidAdds()).append("\n");
        sb.append("Enterprise Adds,").append(data.getEnterpriseAdds()).append("\n");
        return sb.toString().getBytes();
    }

    // ─── PDF builder ──────────────────────────────────────────────────────────

    private byte[] buildPdf(String title, String subtitle, Map<String, String> rows) throws IOException {
        log.debug("Building PDF document title='{}' subtitle='{}' rows={}", title, subtitle, rows.size());
        try (PDDocument doc = new PDDocument()) {
            PDPage page = new PDPage(PDRectangle.A4);
            doc.addPage(page);

            PDType1Font fontBold = new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD);
            PDType1Font fontRegular = new PDType1Font(Standard14Fonts.FontName.HELVETICA);

            float pageHeight = PDRectangle.A4.getHeight();
            float yStart = pageHeight - MARGIN;

            try (PDPageContentStream cs = new PDPageContentStream(doc, page)) {
                float y = yStart;

                // Header bar
                cs.setNonStrokingColor(0.18f, 0.47f, 0.71f);
                cs.addRect(MARGIN, y - 40, CONTENT_WIDTH, 40);
                cs.fill();

                // Title
                cs.setNonStrokingColor(1f, 1f, 1f);
                cs.beginText();
                cs.setFont(fontBold, 16);
                cs.newLineAtOffset(MARGIN + 10, y - 27);
                cs.showText(title);
                cs.endText();

                y -= 55;

                // Subtitle
                cs.setNonStrokingColor(0.3f, 0.3f, 0.3f);
                cs.beginText();
                cs.setFont(fontRegular, 10);
                cs.newLineAtOffset(MARGIN, y);
                cs.showText(subtitle);
                cs.endText();

                y -= 8;

                // Divider line
                cs.setStrokingColor(0.18f, 0.47f, 0.71f);
                cs.setLineWidth(1f);
                cs.moveTo(MARGIN, y);
                cs.lineTo(MARGIN + CONTENT_WIDTH, y);
                cs.stroke();

                y -= LINE_HEIGHT + 4;

                // Rows
                float colLabel = MARGIN + 10;
                float colValue = MARGIN + 230;
                boolean shade = false;

                for (Map.Entry<String, String> entry : rows.entrySet()) {
                    if (y < MARGIN + LINE_HEIGHT) {
                        cs.close();
                        PDPage newPage = new PDPage(PDRectangle.A4);
                        doc.addPage(newPage);
                        // reopen on new page — simplified: just continue
                        break;
                    }

                    if (entry.getKey().startsWith("──")) {
                        cs.setStrokingColor(0.8f, 0.8f, 0.8f);
                        cs.setLineWidth(0.5f);
                        cs.moveTo(MARGIN, y - 2);
                        cs.lineTo(MARGIN + CONTENT_WIDTH, y - 2);
                        cs.stroke();
                        y -= LINE_HEIGHT * 0.6f;
                        shade = false;
                        continue;
                    }

                    if (shade) {
                        cs.setNonStrokingColor(0.95f, 0.97f, 1f);
                        cs.addRect(MARGIN, y - LINE_HEIGHT + 4, CONTENT_WIDTH, LINE_HEIGHT);
                        cs.fill();
                    }
                    shade = !shade;

                    cs.setNonStrokingColor(0.2f, 0.2f, 0.2f);
                    cs.beginText();
                    cs.setFont(fontBold, 9);
                    cs.newLineAtOffset(colLabel, y - 4);
                    cs.showText(entry.getKey());
                    cs.endText();

                    cs.setNonStrokingColor(0.1f, 0.1f, 0.1f);
                    cs.beginText();
                    cs.setFont(fontRegular, 9);
                    cs.newLineAtOffset(colValue, y - 4);
                    cs.showText(entry.getValue() != null ? entry.getValue() : "—");
                    cs.endText();

                    y -= LINE_HEIGHT;
                }

                // Footer
                float footerY = MARGIN - 10;
                cs.setNonStrokingColor(0.6f, 0.6f, 0.6f);
                cs.beginText();
                cs.setFont(fontRegular, 7);
                cs.newLineAtOffset(MARGIN, footerY);
                cs.showText("TeleConnect — Module 2.7 Analytics & Reporting  |  Generated: "
                        + java.time.LocalDateTime.now().toString().substring(0, 19));
                cs.endText();
            }

            ByteArrayOutputStream out = new ByteArrayOutputStream();
            doc.save(out);
            return out.toByteArray();
        }
    }

    // ─── Helpers ──────────────────────────────────────────────────────────────

    private TelecomReport findReport(Long reportId) {
        log.debug("Looking up report reportId={}", reportId);
        return telecomReportRepository.findById(reportId)
                .orElseThrow(() -> new ResourceNotFoundException("Report not found with ID: " + reportId));
    }

    private Map<String, Object> parseMetrics(String metricsJson) {
        log.debug("Parsing metrics json length={}", metricsJson != null ? metricsJson.length() : 0);
        try {
            return objectMapper.readValue(metricsJson, new TypeReference<>() {});
        } catch (Exception e) {
            log.error("Failed to parse report metrics JSON", e);
            throw new AnalyticsException("Failed to parse report metrics: " + e.getMessage());
        }
    }

    private String csvEscape(String value) {
        if (value == null) return "";
        if (value.contains(",") || value.contains("\"") || value.contains("\n")) {
            return "\"" + value.replace("\"", "\"\"") + "\"";
        }
        return value;
    }
}
